pne2twitter:
  _attributes:
    caption:        "「つ」pne→twitter"
    enable_pc:      true
    enable_mobile:  true
  DUMMY:
    Name:         "DUMMY"
    Caption:        "ダミー(入力必要なし)"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
pne2mixi:
  _attributes:
    caption:        "【未】「み」pne→mixi日記"
    enable_pc:      true
    enable_mobile:  true
  MIXIUSER:
    Name:           "MIXIUSER"
    Caption:        "mixi ログインアドレス"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
  MIXIPASS:
    Name:           "MIXIPASS"
    Caption:        "mixi パスワード"
    FormType:       "password"
    ValueType:      "pass"    
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  MIXIID:
    Name:           "MIXIID"
    Caption:        "mixi ID"
    FormType:       "input"
    ValueType:      "pass"    
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
pne2mixivoice:
  _attributes:
    caption:        "【未】「ぼ」pne→mixiボイス"
    enable_pc:      true
    enable_mobile:  true
  DUMMYVOICE:
    Name:           "DUMMYVOICE"
    Caption:        "ダミー(入力必要なし)"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
wordpressSites:
  _attributes:
    caption:        "【未】「わ」pne→WordPress"
    enable_pc:      true
    enable_mobile:  true
  WPKEYWORD1:
    Name:           "WPKEYWORD1"
    Caption:        "1)キーワード"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPURL1:
    Name:           "WPURL1"
    Caption:        "1)WordPressURL ※最後は/"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPID1:
    Name:           "WPID1"
    Caption:        "1)WordPressID"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPPASS1:
    Name:           "WPPASS1"
    Caption:        "1)WordPressPassword"
    FormType:       "password"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPCATEGORY1:
    Name:           "WPCATEGORY1"
    Caption:        "1)WordPressCategory"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPTAG1:
    Name:           "WPTAG1"
    Caption:        "1)WordPressTAG"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
wordpressSites2:
  _attributes:
    caption:        "【未】「ぷ」pne→WordPress"
    enable_pc:      true
    enable_mobile:  true
  WPKEYWORD2:
    Name:           "WPKEYWORD2"
    Caption:        "2)キーワード"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPURL2:
    Name:           "WPURL2"
    Caption:        "2)WordPressURL ※最後は/"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPID2:
    Name:           "WPID2"
    Caption:        "2)WordPressID"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPPASS2:
    Name:           "WPPASS2"
    Caption:        "2)WordPressPassword"
    FormType:       "password"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPCATEGORY2:
    Name:           "WPCATEGORY2"
    Caption:        "2)WordPressCategory"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  WPTAG2:
    Name:           "WPTAG2"
    Caption:        "2)WordPressTAG"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
RTM:
  _attributes:
    caption:        "【未】「り」pne→RememberTheMilk"
    enable_pc:      true
    enable_mobile:  true
  RTMMAIL:
    Name:           "RTMMAIL"
    Caption:        "投稿メールアドレス*importがついているもの"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
mail2pne:
  _attributes:
    caption:        "【未】mail→pne"
    enable_pc:      true
    enable_mobile:  true
  MAILKEYWORD:
    Name:           "MAILKEYWORD"
    Caption:        "メール投稿用のキーワード"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
twitter2pne:
  _attributes:
    caption:        "【未】twitter→pne"
    enable_pc:      true
    enable_mobile:  true
  TWITTERDIRECT:
    Name:           "TWITTERDIRECT"
    Caption:        "【ラボ機能】twitterダイレクトモード"
    FormType:       "radio"
    Choices:        {1: "使う",2: "使わない"}
    Default:        "2"
    ValueType:      "int"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  TWITTERDIRECT_KEYWORD:
    Name:           "TWITTERDIRECT_KEYWORD"
    Caption:        "【ラボ機能】twitterダイレクトモードの投稿キーワード"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  TWITTER_EXCLUDE:
    Name:           "TWITTER_EXCLUDE"
    Caption:        "文頭にこのキーワードが入っていたら投稿しない（半角スペース区切り）"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
twitter2pne2:
  _attributes:
    caption:        "twitter→pne"
    enable_pc:      true
    enable_mobile:  true
agent2pne:
  _attributes:
    caption:        "繰り返し自動投稿"
    enable_pc:      true
    enable_mobile:  true
  AUTOPOSTBODY24_1:
    Name:           "AUTOPOSTBODY24_1"
    Caption:        "24時間自動投稿内容<br /><small>※キーワード付きで設定してください。</small>"
    FormType:       "textarea"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  AUTOPOSTBODY24_2:
    Name:           "AUTOPOSTBODY24_2"
    Caption:        "24時間自動投稿内容<br /><small>※キーワード付きで設定してください。</small>"
    FormType:       "textarea"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  AUTOPOSTBODY3_1:
    Name:           "AUTOPOSTBODY3_1"
    Caption:        "3日おき自動投稿内容<br /><small>※キーワード付きで設定してください。</small>"
    FormType:       "textarea"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  AUTOPOSTBODY3_2:
    Name:           "AUTOPOSTBODY3_2"
    Caption:        "3日おき自動投稿内容<br /><small>※キーワード付きで設定してください。</small>"
    FormType:       "textarea"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  AUTOPOSTBODY7_1:
    Name:           "AUTOPOSTBODY7_1"
    Caption:        "7日おき自動投稿内容<br /><small>※キーワード付きで設定してください。</small>"
    FormType:       "textarea"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  AUTOPOSTBODY7_2:
    Name:           "AUTOPOSTBODY7_2"
    Caption:        "7日おき自動投稿内容<br /><small>※キーワード付きで設定してください。</small>"
    FormType:       "textarea"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
sepalator:
  _attributes:
    caption:        "件名本文セパレータ"
    enable_pc:      true
    enable_mobile:  true
  SEPARATOR_LF:
    Name:           "SEPARATOR_LF"
    Caption:        "改行をセパレータにする？"
    FormType:       "radio"
    Choices:        {"1":"する","2":"しない"}
    Default:        "1"
    ValueType:      "int"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  SEPARATOR_KEYWORDS:
    Name:           "SEPARATOR_KEYWORDS"
    Caption:        "その他のセパレータ文字列（半角スペース区切り）"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
calendar2pne:
  _attributes:
    caption:        "【ラボ機能】GoogleCalendar→pne"
    enable_pc:      true
    enable_mobile:  true
  GOOGLEID:
    Name:           "GOOGLEID"
    Caption:        "カレンダー用GOOGLEID"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  GOOGLEPASS:
    Name:           "GOOGLEPASS"
    Caption:        "GOOGLEパスワード"
    FormType:       "password"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
Ameba:
  _attributes:
    caption:        "【ラボ機能】「な」Amebaなう"
    enable_pc:      true
    enable_mobile:  true
  AMEBAID:
    Name:           "AMEBAID"
    Caption:        "AMEBAID"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  AMEBAPASS:
    Name:           "AMEBAPASS"
    Caption:        "パスワード"
    FormType:       "password"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
OpenPNEACT:
  _attributes:
    caption:        "【ラボ機能】「あ」pne→OpenPNEアクティビティ"
    enable_pc:      true
    enable_mobile:  true
  SNSURL_ACT:
    Name:           "SNSURL_ACT"
    Caption:        "1)SNSURL ※最後は/"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  SNSID_ACT:
    Name:           "SNSID_ACT"
    Caption:        "1)SNSID"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  SNSPASS_ACT:
    Name:           "SNSPASS_ACT"
    Caption:        "1)SNSPASSWORD"
    FormType:       "password"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
OpenPNEACT2:
  _attributes:
    caption:        "【ラボ機能】「く」pne→OpenPNEアクティビティ"
    enable_pc:      true
    enable_mobile:  true
  SNSURL_ACT2:
    Name:           "SNSURL_ACT2"
    Caption:        "1)SNSURL ※最後は/"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  SNSID_ACT2:
    Name:           "SNSID_ACT2"
    Caption:        "1)SNSID"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
  SNSPASS_ACT2:
    Name:           "SNSPASS_ACT2"
    Caption:        "1)SNSPASSWORD"
    FormType:       "password"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
Facebook:
  _attributes:
    caption:        "【ラボ機能】「ふ」pne→Facebook"
    enable_pc:      true
    enable_mobile:  true
  FB_SESSION:
    Name:           "FB_SESSION"
    Caption:        "セッションキー"
    FormType:       "input"
    ValueType:      "pass"
    IsRegist:       false
    IsConfig:       true
    IsRequired:     false
    IsConfirm:      false
